# Generated by Django 2.1.5 on 2019-01-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='category',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
